"""
LangGraph state shared across all Norma pipeline nodes.
"""

from typing import Annotated, NotRequired, TypedDict


def _merge_dicts(a: dict, b: dict) -> dict:
    """Reducer for spec_artefacts: merges updates from parallel specialist nodes."""
    return {**a, **b}


class SpecRecommendation(TypedDict):
    """
    Full brief for one specialist, generated by the Spec Advisor.

    language             — human label (e.g. "RFC 2119", "OpenAPI 3.1")
    artefact_key         — slug used as key in spec_artefacts (e.g. "rfc2119")
    rationale            — why this standard is needed for this requirement
    depends_on           — artefact_keys that must be produced first
    requirement_segments — verbatim excerpt(s) from the normalised requirement that
                           this specialist is responsible for; the specialist receives
                           only these parts, not the full requirement
    role                 — CRISPE Role field for the specialist shell
    insight              — CRISPE Insight: domain context tailored to this requirement
    statement            — CRISPE Statement: exact output format / structure required
    """
    language: str
    artefact_key: str
    rationale: str
    depends_on: list[str]
    requirement_segments: str
    role: str
    insight: str
    statement: str


class EnvironmentOption(TypedDict):
    """
    One ranked environment option produced by the Environment Advisor.

    runtime         — e.g. "Python 3.12 + FastAPI"
    framework       — primary framework / library
    deployment      — deployment target (e.g. "Docker / AWS Lambda")
    rationale       — why this option suits the requirement
    rank            — 1 = most recommended
    """
    runtime: str
    framework: str
    deployment: str
    rationale: str
    rank: int


class NormaState(TypedDict, total=False):
    # INTAKE
    raw_requirement: str
    normalised_requirement: str
    actors: list[str]
    external_deps: list[str]

    # PIPELINE 1 — GHERKIN SPECIALIST (permanent)
    gherkin_content: NotRequired[str]   # alias: gherkin_business after Stage 1 Gate
    gherkin_business: NotRequired[str]  # immutable after Stage 1 Gate sign-off

    # PIPELINE 1 — ENVIRONMENT ADVISOR
    environment_options: NotRequired[list[EnvironmentOption]]

    # PIPELINE 1 → PIPELINE 2 boundary (set by human / harness)
    selected_environment: NotRequired[EnvironmentOption]

    # PIPELINE 1 — STAGE 1 GATE
    stage1_passed: NotRequired[bool]
    stage1_feedback: NotRequired[str]

    # PIPELINE 2 — SPEC ADVISOR (permanent)
    spec_advice: NotRequired[list[SpecRecommendation]]

    # PIPELINE 2 — SPEC SPECIALIST shell — set by Send per dispatch
    current_recommendation: NotRequired[SpecRecommendation]

    # PIPELINE 2 — SPEC SPECIALIST artefacts — merged from parallel specialist nodes
    spec_artefacts: NotRequired[Annotated[dict[str, str], _merge_dicts]]

    # PIPELINE 2 — TECHNICAL GHERKIN SPECIALIST
    gherkin_technical: NotRequired[str]

    # PIPELINE 2 — STAGE 2 GATE (replaces CAI gate in two-stage mode)
    gate_passed: NotRequired[bool]
    gate_feedback: NotRequired[str]
    revision_count: NotRequired[int]
