"""
LangGraph state shared across all Norma pipeline nodes.
"""

from typing import Annotated, NotRequired, TypedDict


def _merge_dicts(a: dict, b: dict) -> dict:
    """Reducer for spec_artefacts: merges updates from parallel specialist nodes."""
    return {**a, **b}


class SpecRecommendation(TypedDict):
    """
    Full brief for one specialist, generated by the Spec Advisor.

    language             — human label (e.g. "RFC 2119", "OpenAPI 3.1")
    artefact_key         — slug used as key in spec_artefacts (e.g. "rfc2119")
    rationale            — why this standard is needed for this requirement
    depends_on           — artefact_keys that must be produced first
    requirement_segments — verbatim excerpt(s) from the normalised requirement that
                           this specialist is responsible for; the specialist receives
                           only these parts, not the full requirement
    role                 — CRISPE Role field for the specialist shell
    insight              — CRISPE Insight: domain context tailored to this requirement
    statement            — CRISPE Statement: exact output format / structure required
    """
    language: str
    artefact_key: str
    rationale: str
    depends_on: list[str]
    requirement_segments: str
    role: str
    insight: str
    statement: str


class NormaState(TypedDict, total=False):
    # INTAKE
    raw_requirement: str
    normalised_requirement: str
    actors: list[str]
    external_deps: list[str]

    # GHERKIN SPECIALIST (permanent)
    gherkin_content: NotRequired[str]

    # SPEC ADVISOR (permanent)
    spec_advice: NotRequired[list[SpecRecommendation]]

    # SPEC SPECIALIST shell — set by Send per dispatch, consumed by shell node
    current_recommendation: NotRequired[SpecRecommendation]

    # SPEC SPECIALIST artefacts — Annotated so parallel specialist nodes merge cleanly
    spec_artefacts: NotRequired[Annotated[dict[str, str], _merge_dicts]]

    # CAI GATE
    gate_passed: NotRequired[bool]
    gate_feedback: NotRequired[str]
    revision_count: NotRequired[int]
